---
- name: Install Redis
  apt:
    pkg: redis-server
    state: installed
    update_cache: true
  notify: Start Redis

- name: Install php-redis
  apt:
    pkg: php-redis
    state: installed
    update_cache: true
  notify: Restart php-fpm

- name: Configure Redis
  template:
    src: redis.conf.j2
    dest: "{{ redis_config_path }}/redis.conf"
    mode: 0640
  notify: Restart Redis

- name: Add web user to redis group
  user:
    name: "{{ item }}"
    groups: redis
    append: yes
  when: redis_unixsocket != ""
  with_items: "{{ redis_socket_users }}"

- name: Set Redis to Run on Boot
  service:
    name: redis-server
    state: started
    enabled: yes
